services:
  # Backend API service
  - type: web
    name: stocknewsscanner-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m gunicorn server:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      # connection_string should be set in the Render dashboard
      # The MONGO_URL below is just a fallback
      - key: DB_NAME
        value: stock_news_db
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8001
      - key: RENDER
        value: true

  # Frontend service
  - type: web
    name: stocknewsscanner-frontend
    env: node
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && yarn global add serve && serve -s build -l $PORT
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://stocknewsscanner-api.onrender.com/api