services:
  # Backend API service
  - type: web
    name: connect-the-plots-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEWS_API_KEY
        sync: false
    healthCheckPath: /health
    buildCommand: echo "Docker build handled by Dockerfile"
    autoDeploy: true

  # Frontend web service
  - type: web
    name: connect-the-plots-frontend
    runtime: node
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: connect-the-plots-backend
          type: web
          property: url
      - key: NODE_VERSION
        value: 16.13.0
    autoDeploy: true
